//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_User()
        {
            this.TBL_Exam = new HashSet<TBL_Exam>();
        }
    
        public long userId { get; set; }
        public string userName { get; set; }
        public string userLoginName { get; set; }
        public string userPassword { get; set; }
        public string userImage { get; set; }
        public Nullable<int> userType { get; set; }
        public Nullable<int> userCreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Exam> TBL_Exam { get; set; }
        public virtual TBL_UserType TBL_UserType { get; set; }
    }
}
