//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Exam()
        {
            this.TBL_Question = new HashSet<TBL_Question>();
        }
    
        public long examId { get; set; }
        public string examName { get; set; }
        public Nullable<long> examCreatedBy { get; set; }
        public string examAppearCode { get; set; }
        public Nullable<bool> examStatus { get; set; }
    
        public virtual TBL_User TBL_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Question> TBL_Question { get; set; }
    }
}
